"""
Replicates the two-panel reversal-learning figure, following the procedure
in Palminteri, Wyart & Koechlin (2017, Trends in Cognitive Sciences, Box 1
/ Figure I): ground-truth choice data are generated by a Q-learning agent
(learning rate alpha) whose latent values are corrupted by additive
Gaussian noise (std sigma) at the moment of choice. Two single-parameter
heuristic models are then compared:
  (A, left)  Predictive performance: Repetition & WS-LS models fit to /
             fed the "real" (Q-learning-agent-generated) choice-outcome
             history, scored on next-choice prediction, with a
             log-likelihood inset comparing the two models.
  (A, right) Generative performance: same fitted models run forward on
             their own (using only the task's true reward contingencies)
             to see what behavior they produce from scratch.

Run: python3 reversal_learning_figure.py [--no_loglik_bars] [--no_title] [--legend {all,predictive,none}]
Outputs: CSVs in data/, PNGs in figures/ (legends saved separately as *_legend.png)
"""

import argparse
import csv
import os
import sys
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib.gridspec import GridSpec
from matplotlib.patches import Patch

sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
import plotting_utils
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), "..", "rl_waltmann"))
from generate_gen_plots import plot_bandit_choice_trends_single_axis, REVERSAL_POINTS as WALTMANN_REVERSAL_POINTS

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(SCRIPT_DIR, "data")
FIGURES_DIR = os.path.join(SCRIPT_DIR, "figures")
BASE_FONT = 24 # ~10pt at 12-inch reference width, scaled for these compact multi-panel figures
FIGSIZE_ALONE = (8, 6)  # standalone panels (predictive or generative) are square
os.makedirs(DATA_DIR, exist_ok=True)
os.makedirs(FIGURES_DIR, exist_ok=True)

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument("--no_loglik_bars", dest="show_loglik_bars", action="store_false",
                     help="Skip drawing the log-likelihood inset bar chart on the predictive panel(s)")
parser.add_argument("--no_title", dest="show_title", action="store_false",
                     help="Hide the panel title (e.g. 'Predictive performance / model fits')")
parser.add_argument("--legend", choices=["all", "predictive", "none"], default="all",
                     help="Which panels get the on-axis legend (Human/Repetition/WS-LS) and the "
                          "separate *_legend.png file. 'all' (default): predictive column of the "
                          "combined figure + both standalone panels. 'predictive': predictive "
                          "panels only (combined figure's predictive column + standalone "
                          "predictive panel) -- the generative panels never get one. 'none': "
                          "no panel gets one.")
parser.add_argument("--data_source", choices=["simulated", "real"], default="real",
                     help="'real' (default): fit to actual human choice/reward histories from "
                          "rl_waltmann/data/in/. 'simulated': ground-truth data from the "
                          "Q-learning agent instead.")
parser.add_argument("--real_data_csv", default=None,
                     help="CSV path to use when --data_source=real (default: "
                          "rl_waltmann/data/in/test_waltmann_data_cleaned.csv)")
parser.add_argument("--max_trial", type=int, default=None,
                     help="Truncate the plotted trial range to [1, max_trial] (fitting still "
                          "uses the full data). Only the plots are cropped -- CSVs still cover "
                          "all trials. Default: full range for --data_source=simulated; "
                          "first-reversal-trial + 14 (matching rl_waltmann's own default "
                          "plotting window) for --data_source=real, so the real-data figure "
                          "shows the first reversal plus its recovery instead of all 5 blocks.")
parser.set_defaults(show_loglik_bars=False, show_title=True)
args = parser.parse_args()
show_legend_predictive = args.legend in ("all", "predictive")
show_legend_generative = args.legend == "all"

from reversal_learning_sim import (
    N_TRIALS, REVERSAL, P_HIGH, P_LOW,
    simulate_qlearning_agent, fit_repetition, predictive_curve_repetition,
    simulate_generative_repetition, fit_wsls, predictive_curve_wsls,
    simulate_generative_wsls, mean_trial_loglik, load_waltmann_data,
)

# ----------------------------------------------------------------------
# Config
# ----------------------------------------------------------------------
N_SUBJECTS = 32        # simulated "real" sessions (ground truth agent); overridden below if --data_source=real
N_GEN_SIMS_PER_SUBJECT = 50  # generative simulations per fitted subject
ALPHA_TRUE, NOISE_SD_TRUE = 0.1, 0.2   # ground-truth Q-learning agent params (paper values)
REAL_DATA_CSV = args.real_data_csv or os.path.join(
    SCRIPT_DIR, "..", "rl_waltmann", "data", "in", "test_waltmann_data_cleaned.csv")

COL_DATA = "black"
COL_REP = "#8fae3c"     # olive/green
COL_WSLS = "#d18a35"    # orange
COL_HIGH = "#7b2d8b"    # purple (80% option)
COL_LOW = "#3b5aa0"     # blue (20% option)

rng = np.random.default_rng(42)
random.seed(42)  # ProbabilisticWinStayLoseSwitch uses stdlib `random` internally

# Filename tag + data-curve legend label, so simulated and real-data runs write to
# separate files instead of overwriting each other's outputs.
TAG = "" if args.data_source == "simulated" else "_real"

# ----------------------------------------------------------------------
# 1. Ground-truth "real" data: either simulated from a Q-learning agent, or
#    loaded from real subjects' choice/reward histories (--data_source=real).
#    REVERSAL_POINTS_1IDX is the 1-indexed trial number of the first trial of
#    each new block; REVERSAL_POINTS_0IDX is the same, 0-indexed, as consumed
#    by reward_prob_A/B and simulate_generative_wsls.
# ----------------------------------------------------------------------
if args.data_source == "real":
    choices, rewards, subject_ids, N_TRIALS, REVERSAL_POINTS_0IDX = load_waltmann_data(
        REAL_DATA_CSV, reversal_points_1idx=WALTMANN_REVERSAL_POINTS)
    N_SUBJECTS = len(subject_ids)
    REVERSAL_POINTS_1IDX = tuple(WALTMANN_REVERSAL_POINTS)
    REVERSAL = REVERSAL_POINTS_0IDX[0]
    print(f"Loaded real data: {N_SUBJECTS} subjects, {N_TRIALS} trials, "
          f"reversals at {REVERSAL_POINTS_1IDX} from {REAL_DATA_CSV}")
else:
    choices, rewards = simulate_qlearning_agent(N_SUBJECTS, ALPHA_TRUE, NOISE_SD_TRUE, rng)
    REVERSAL_POINTS_0IDX = (REVERSAL,)
    REVERSAL_POINTS_1IDX = (REVERSAL + 1,)

# Trial range shown in the plots only (fitting above/below always uses the full
# N_TRIALS). Real data defaults to first-reversal + 14 trials -- enough to see
# the post-reversal dip and recovery -- rather than all 5 Waltmann blocks at once.
if args.max_trial is not None:
    PLOT_MAX_TRIAL = args.max_trial
elif args.data_source == "real":
    PLOT_MAX_TRIAL = min(N_TRIALS, REVERSAL_POINTS_1IDX[0] + 14)
else:
    PLOT_MAX_TRIAL = N_TRIALS

data_rate_A = (choices == 0).mean(axis=0)
data_sem_A = (choices == 0).std(axis=0) / np.sqrt(N_SUBJECTS)

# ----------------------------------------------------------------------
# 2. Fit models per subject on real data; build predictive curves
# ----------------------------------------------------------------------
pred_rep = np.zeros((N_SUBJECTS, N_TRIALS))
pred_wsls = np.zeros((N_SUBJECTS, N_TRIALS))
ll_rep = np.zeros(N_SUBJECTS)
ll_wsls = np.zeros(N_SUBJECTS)

rho_fits = np.zeros(N_SUBJECTS)
wsls_P_fits = np.zeros(N_SUBJECTS)

for s in range(N_SUBJECTS):
    c, r = choices[s], rewards[s]

    rho = fit_repetition(c)
    p_rep = predictive_curve_repetition(c, rho)
    pred_rep[s] = p_rep
    ll_rep[s] = mean_trial_loglik(c, p_rep)
    rho_fits[s] = rho

    P = fit_wsls(c, r)
    p_wsls = predictive_curve_wsls(c, r, P)
    pred_wsls[s] = p_wsls
    ll_wsls[s] = mean_trial_loglik(c, p_wsls)
    wsls_P_fits[s] = P

pred_rep_mean = pred_rep.mean(axis=0)
pred_rep_sem = pred_rep.std(axis=0) / np.sqrt(N_SUBJECTS)
pred_wsls_mean = pred_wsls.mean(axis=0)
pred_wsls_sem = pred_wsls.std(axis=0) / np.sqrt(N_SUBJECTS)

ll_rep_bar = ll_rep.mean()
ll_wsls_bar = ll_wsls.mean()

# ----------------------------------------------------------------------
# 3. Generative simulations using each subject's fitted parameters
# ----------------------------------------------------------------------
gen_rep_all = np.zeros((N_SUBJECTS * N_GEN_SIMS_PER_SUBJECT, N_TRIALS))
gen_wsls_all = np.zeros((N_SUBJECTS * N_GEN_SIMS_PER_SUBJECT, N_TRIALS))

for s in range(N_SUBJECTS):
    sl = slice(s * N_GEN_SIMS_PER_SUBJECT, (s + 1) * N_GEN_SIMS_PER_SUBJECT)
    gen_rep_all[sl] = simulate_generative_repetition(rho_fits[s], N_GEN_SIMS_PER_SUBJECT, rng, n_trials=N_TRIALS)
    gen_wsls_all[sl] = simulate_generative_wsls(wsls_P_fits[s], N_GEN_SIMS_PER_SUBJECT, rng,
                                                 n_trials=N_TRIALS, reversal_points=REVERSAL_POINTS_0IDX)

gen_rep_rate = (gen_rep_all == 0).mean(axis=0)
gen_rep_sem = (gen_rep_all == 0).std(axis=0) / np.sqrt(gen_rep_all.shape[0])
gen_wsls_rate = (gen_wsls_all == 0).mean(axis=0)
gen_wsls_sem = (gen_wsls_all == 0).std(axis=0) / np.sqrt(gen_wsls_all.shape[0])


def _to_long_df(arr, transform=lambda a: a):
    """(n_runs, N_TRIALS) array -> long df with columns model_id/trial_num/
    chose_preferred, the shape rl_waltmann's aggregate_trend/
    plot_bandit_choice_trends_single_axis expect."""
    n_runs, n_trials = arr.shape
    return pd.DataFrame({
        "model_id": np.repeat(np.arange(n_runs), n_trials),
        "trial_num": np.tile(np.arange(1, n_trials + 1), n_runs),
        "chose_preferred": transform(arr).flatten(),
    })


# Long-format frames feeding rl_waltmann's plot_bandit_choice_trends_single_axis,
# so this figure's choice-rate panels are drawn by the exact same function as
# generate_gen_plots.py rather than a separate hand-rolled implementation.
data_long_df = _to_long_df(choices, lambda a: (a == 0).astype(int))
pred_rep_long_df = _to_long_df(pred_rep)
pred_wsls_long_df = _to_long_df(pred_wsls)
gen_rep_long_df = _to_long_df(gen_rep_all, lambda a: (a == 0).astype(int))
gen_wsls_long_df = _to_long_df(gen_wsls_all, lambda a: (a == 0).astype(int))

ground_truth_label = "Ground-truth agent" if args.data_source == "simulated" else "Real data"
print(f"{ground_truth_label}: peak choice(A) ~ {data_rate_A[10:REVERSAL].mean():.2f}, "
      f"late choice(A) ~ {data_rate_A[-10:].mean():.2f}")
print(f"Fitted Repetition: rho = {rho_fits.mean():.3f}")
print(f"Fitted WSLS (single parameter): P = {wsls_P_fits.mean():.3f}")
print(f"Mean predictive log-lik/trial: Repetition={ll_rep_bar:.3f}, WSLS={ll_wsls_bar:.3f}")

# ----------------------------------------------------------------------
# 4. Save all data
# ----------------------------------------------------------------------

# 4a. Task / simulation config as CSV
with open(f"{DATA_DIR}/reversal_learning_task_config{TAG}.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(["parameter", "value"])
    config_rows = [
        ("data_source", args.data_source),
        ("n_trials", N_TRIALS),
        ("max_trial_plotted", PLOT_MAX_TRIAL),
        ("reversal_points_1idx", ";".join(str(r) for r in REVERSAL_POINTS_1IDX)),
        ("p_high", P_HIGH), ("p_low", P_LOW),
        ("n_subjects", N_SUBJECTS),
        ("n_gen_sims_per_subject", N_GEN_SIMS_PER_SUBJECT),
    ]
    if args.data_source == "simulated":
        config_rows += [("alpha_true", ALPHA_TRUE), ("noise_sd_true", NOISE_SD_TRUE)]
    else:
        config_rows += [("real_data_csv", REAL_DATA_CSV)]
    for name, val in config_rows:
        writer.writerow([name, val])
print(f"Saved reversal_learning_task_config{TAG}.csv")

# 4b. Trial-level summary curves (means + SEMs) as CSV, for plotting/reuse elsewhere
with open(f"{DATA_DIR}/reversal_learning_summary{TAG}.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerow([
        "trial", "data_mean", "data_sem",
        "pred_repetition_mean", "pred_repetition_sem",
        "pred_wsls_mean", "pred_wsls_sem",
        "gen_repetition_mean", "gen_repetition_sem",
        "gen_wsls_mean", "gen_wsls_sem",
    ])
    for t in range(N_TRIALS):
        writer.writerow([
            t + 1, data_rate_A[t], data_sem_A[t],
            pred_rep_mean[t], pred_rep_sem[t],
            pred_wsls_mean[t], pred_wsls_sem[t],
            gen_rep_rate[t], gen_rep_sem[t],
            gen_wsls_rate[t], gen_wsls_sem[t],
        ])
print(f"Saved reversal_learning_summary{TAG}.csv")

# 4c. Per-subject fitted parameters + predictive fit quality as CSV
with open(f"{DATA_DIR}/reversal_learning_subject_fits{TAG}.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerow([
        "subject", "repetition_rho", "wsls_P",
        "loglik_per_trial_repetition", "loglik_per_trial_wsls",
    ])
    for s in range(N_SUBJECTS):
        writer.writerow([
            subject_ids[s] if args.data_source == "real" else s,
            rho_fits[s], wsls_P_fits[s], ll_rep[s], ll_wsls[s],
        ])
print(f"Saved reversal_learning_subject_fits{TAG}.csv")

# 4d. Raw per-subject, per-trial choices/rewards as CSV (long format)
with open(f"{DATA_DIR}/reversal_learning_raw_trials{TAG}.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(["subject", "trial", "choice", "reward"])
    for s in range(N_SUBJECTS):
        subj = subject_ids[s] if args.data_source == "real" else s
        for t in range(N_TRIALS):
            writer.writerow([subj, t + 1, int(choices[s, t]), int(rewards[s, t])])
print(f"Saved reversal_learning_raw_trials{TAG}.csv")

# 4e. Per-subject, per-trial PREDICTIVE probabilities (teacher-forced fits) as CSV
with open(f"{DATA_DIR}/reversal_learning_predictive_curves{TAG}.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(["subject", "trial", "pred_prob_repetition", "pred_prob_wsls"])
    for s in range(N_SUBJECTS):
        subj = subject_ids[s] if args.data_source == "real" else s
        for t in range(N_TRIALS):
            writer.writerow([subj, t + 1, pred_rep[s, t], pred_wsls[s, t]])
print(f"Saved reversal_learning_predictive_curves{TAG}.csv")

# 4f. Raw GENERATIVE simulated choices (closed-loop, model's own trajectories) as CSV
with open(f"{DATA_DIR}/reversal_learning_generative_trials{TAG}.csv", "w", newline="") as f:
    writer = csv.writer(f)
    writer.writerow(["model", "subject", "sim_within_subject", "trial", "choice"])
    for s in range(N_SUBJECTS):
        subj = subject_ids[s] if args.data_source == "real" else s
        for k in range(N_GEN_SIMS_PER_SUBJECT):
            row_idx = s * N_GEN_SIMS_PER_SUBJECT + k
            for t in range(N_TRIALS):
                writer.writerow(["repetition", subj, k, t + 1, int(gen_rep_all[row_idx, t])])
                writer.writerow(["wsls", subj, k, t + 1, int(gen_wsls_all[row_idx, t])])
print(f"Saved reversal_learning_generative_trials{TAG}.csv")

# ----------------------------------------------------------------------
# 5. Plot
# ----------------------------------------------------------------------
trials = np.arange(1, N_TRIALS + 1)

titles = ["Predictive performance\nmodel fits", "Generative performance\nmodel simulations"]


def _preferred_prob_curve(trials_1idx, reversal_points_1idx):
    """P_HIGH/P_LOW schedule for the option preferred in the first block,
    flipping at each 1-indexed trial in `reversal_points_1idx` (the first
    trial of each new block). Generalizes the single-reversal case (one
    flip) to the multi-block real-data schedule (several flips)."""
    n_flips = np.zeros_like(trials_1idx)
    for r in reversal_points_1idx:
        n_flips = n_flips + (trials_1idx >= r).astype(int)
    return np.where(n_flips % 2 == 0, P_HIGH, P_LOW)


def _set_ylabel_choice_a(ax):
    """Replaces the default two-line ylabel set by plot_bandit_choice_trends_single_axis
    ("Choice rate\n(original high-value arm)") with "Choice rate" / "choice A" as two
    stacked, differently-colored lines -- "choice A" colored the same as the "A 80%"
    schedule label above. A single Text can't mix colors, so this is built out of two
    Text objects (rotated 90deg) anchored at the exact same point, following
    matplotlib's "rainbow text" recipe -- with the second one's string prefixed by
    "\\n" so it lands on the native second-line slot. For a rotated Text, matplotlib
    offsets line 2 *perpendicular* to the reading direction (not after it), which is
    exactly the original label's own layout: "Choice rate" sits outboard (away from
    the axis) and the second line sits inboard (closer to it, like "(original
    high-value arm)" did) -- reusing that same anchor point keeps the new label's
    position/spacing identical to the one it replaces."""
    fig = ax.figure
    fig.canvas.draw()  # layout the original ylabel so its position/size are real
    renderer = fig.canvas.get_renderer()
    orig_label = ax.yaxis.label
    label_fontsize = orig_label.get_fontsize()
    bbox = orig_label.get_window_extent(renderer)
    # Extra clearance from the tick labels, beyond what the original label's own
    # labelpad already reserved -- the inboard ("(option A)") column sits closer to
    # the axis than a single-line label would, so it needs a bit more room of its
    # own; scaled the same way generate_gen_plots.py scales the original labelpad.
    fig_width = fig.get_size_inches()[0]
    extra_pad_px = plotting_utils.get_dynamic_labelpad(fig_width, base_pad=10) * fig.dpi / 72
    label_x = ax.transAxes.inverted().transform((bbox.x0 + bbox.width / 2 - extra_pad_px, 0))[0]
    label_y = ax.transAxes.inverted().transform((0, bbox.y0 + bbox.height / 2))[1]
    ax.set_ylabel("")
    from matplotlib.transforms import offset_copy
    ax.text(label_x, label_y, "Choice rate", color="black", transform=ax.transAxes,
             rotation=90, fontsize=label_fontsize, ha="center", va="center")
    inboard_trans = offset_copy(ax.transAxes, fig=fig, x=label_fontsize * 1.2, y=0, units="points")
    ax.text(label_x, label_y, "(option A)", color=COL_HIGH, transform=inboard_trans,
             rotation=90, fontsize=label_fontsize, ha="center", va="center")


def draw_panel(fig, gs, row_top, row_main, grid_col, data_col,
               show_legend=False, show_inset=False, legend_path=None):
    """Draws the reward-schematic strip + choice-rate panel into the given
    figure/gridspec at grid_col, using the data for data_col (0=predictive,
    1=generative). grid_col and data_col differ for standalone single-panel
    figures, where the gridspec has only one column."""
    col = data_col
    # Scaled off the actual figure's width (not a fixed reference), the same
    # way draw_panel's labelpad values are -- so text tuned for the combined
    # (11-inch) figure doesn't look oversized on the 5/6-inch standalone panels.
    fig_width = fig.get_size_inches()[0]
    ax_top = fig.add_subplot(gs[row_top, grid_col])
    p_A = _preferred_prob_curve(trials, REVERSAL_POINTS_1IDX)
    p_B = np.where(p_A == P_HIGH, P_LOW, P_HIGH)
    ax_top.plot(trials, p_A, color=COL_HIGH, lw=2.5, solid_capstyle="butt")
    ax_top.plot(trials, p_B, color=COL_LOW, lw=2.5, solid_capstyle="butt")
    ax_top.set_ylim(0, 1)
    ax_top.set_xlim(1, PLOT_MAX_TRIAL)
    ax_top.axis("off")
    #corner_fontsize = plotting_utils.get_dynamic_fontsize(fig_width, base_font=BASE_FONT)
    ax_top.text(0, P_HIGH, "A 80%  ", ha="right", va="center", color=COL_HIGH)
    ax_top.text(0, P_LOW, "B 20%  ", ha="right", va="center", color=COL_LOW)
    if args.show_title:
        ax_top.set_title(titles[col], pad=10, fontsize=plotting_utils.get_dynamic_fontsize(fig_width, base_font=12))

    ax = fig.add_subplot(gs[row_main, grid_col])

    # Choice-rate curves (data + both models), shading, reversal marker, and
    # axis formatting all come from rl_waltmann/generate_gen_plots.py's
    # plot_bandit_choice_trends_single_axis -- the same function that draws
    # every other task's choice-rate panels -- rather than a reimplementation.
    rep_df = pred_rep_long_df if col == 0 else gen_rep_long_df
    wsls_df = pred_wsls_long_df if col == 0 else gen_wsls_long_df
    plot_bandit_choice_trends_single_axis(
        human_df=data_long_df,
        dfs=[rep_df, wsls_df],
        labels=["Repetition", "WS-LS"],
        colors=[COL_DATA, COL_REP, COL_WSLS],
        trial_col="trial_num",
        bandit_avg_col="chose_preferred",
        reversal_trials=[r - 0.5 for r in REVERSAL_POINTS_1IDX if r <= PLOT_MAX_TRIAL],
        xlim=(1, PLOT_MAX_TRIAL),
        margins=True,
        shade_post_reversal=True,
        shade_color="#888888",
        shade_alpha=0.10,
        ax=ax,
    )

    # Y-axis label: multi-color to match the "A 80%"/"B 20%" schedule text above --
    # "choice A" is set in the same color as "A 80%" since choice rate here always
    # tracks the arm that started out high-value (i.e. choice A).
    _set_ylabel_choice_a(ax)

    if show_legend:
        # human_df's label is hardcoded to "Human" inside the shared function.
        data_label = "Data (Q-learning agent)" if args.data_source == "simulated" else "Human"
        handles, labels_legend = ax.get_legend_handles_labels()
        labels_legend = [data_label if l == "Human" else l for l in labels_legend]
        # Small filled squares instead of the default line-sample handles.
        square_handles = [Patch(facecolor=h.get_color(), edgecolor="none") for h in handles]
        # Sized down from the main tick/label font since this legend has to fit
        # inside the axes alongside the curves, not in its own figure. (Note:
        # called with fig_width as a keyword -- get_dynamic_fontsize's first
        # positional arg is `multiplier`, not `fig_width`.)
        onaxis_fontsize = plotting_utils.get_dynamic_fontsize(fig_width=fig_width, base_font=24)
        ax.legend(square_handles, labels_legend, loc="lower left", frameon=False,
                  fontsize=onaxis_fontsize, handlelength=0.8, handleheight=0.8,
                  borderaxespad=0.6, labelspacing=0.4)

        # Also saved as its own figure so the legend can be reused/positioned
        # freely elsewhere (e.g. combined-figure layouts) at full size.
        legend_fontsize = plotting_utils.get_dynamic_fontsize(fig_width, base_font=BASE_FONT)
        legend_fig = plt.figure(figsize=(4, 1.2))
        legend_ax = legend_fig.add_subplot(111)
        legend_ax.axis("off")
        legend_ax.legend(square_handles, labels_legend, loc="center", frameon=False,
                          fontsize=legend_fontsize, handlelength=1, handleheight=1)
        legend_fig.savefig(legend_path, bbox_inches='tight', pad_inches=0.02, dpi=300, transparent=True)
        plt.close(legend_fig)
        print(f"Saved {legend_path}")

    if show_inset:
        # Top-right: the predictive curves are high there before the reversal
        # and low after, leaving that corner free -- unlike bottom-left, which
        # is now taken by the on-axis legend above.
        ax_inset = ax.inset_axes([0.68, 0.60, 0.28, 0.34])
        ax_inset.bar([0, 1], [ll_wsls_bar, ll_rep_bar],
                     color=[COL_WSLS, COL_REP], width=0.7,
                     edgecolor="black", linewidth=0.8)
        ax_inset.set_xticks([])
        inset_fontsize = plotting_utils.get_dynamic_fontsize(fig_width=fig_width, base_font=8)
        ax_inset.set_ylabel("Log-likelihood", labelpad=2, fontsize=inset_fontsize)
        ax_inset.tick_params(labelsize=inset_fontsize, pad=1)
        ax_inset.set_ylim(min(ll_rep_bar, ll_wsls_bar) * 1.3, 0)
        plotting_utils.remove_bar_frame(ax_inset)
        plotting_utils.style_y_gridlines(ax_inset)

    for spine in ["top", "right"]:
        ax.spines[spine].set_visible(False)


# Margin reserved above the top row: 0.86 leaves headroom for the panel title;
# with --no_title there's nothing to make room for, so reclaim most of it.
GS_TOP = 0.86 if args.show_title else 0.97

# 5a. Combined two-panel figure
fig = plt.figure(figsize=(11, 5.2))
# Sets rcParams (axes.labelsize, xtick/ytick.labelsize, legend.fontsize, ...) off
# this figure's actual width -- the axis/tick labels drawn inside
# plot_bandit_choice_trends_single_axis never take an explicit fontsize, so this
# is the only thing that scales them; base_font=10 targets ~10pt at a 12-inch
# reference width, sized for these compact multi-panel figures rather than
# rl_waltmann's own big standalone ones (which use base_font=20).
plotting_utils.set_dynamic_fontsize(fig_width=11, base_font=BASE_FONT)
gs = GridSpec(2, 2, height_ratios=[0.12, 1], hspace=0.08, wspace=0.28,
              top=GS_TOP, bottom=0.13, left=0.07, right=0.98)
for col in range(2):
    draw_panel(fig, gs, 0, 1, col, col, show_legend=(col == 0 and show_legend_predictive),
               show_inset=(col == 0 and args.show_loglik_bars),
               legend_path=f"{FIGURES_DIR}/reversal_learning_figure{TAG}_legend.png")
plotting_utils.save_panel(fig, f"{FIGURES_DIR}/reversal_learning_figure{TAG}.png", figsize=(11, 5.2))
plt.close(fig)
print(f"Saved reversal_learning_figure{TAG}.png")

# 5b. Predictive panel alone
fig_pred = plt.figure(figsize=FIGSIZE_ALONE)
plotting_utils.set_dynamic_fontsize(fig_width=FIGSIZE_ALONE[0], base_font=BASE_FONT)
gs_pred = GridSpec(2, 1, height_ratios=[0.12, 1], hspace=0.08,
                    top=GS_TOP, bottom=0.13, left=0.13, right=0.97)
draw_panel(fig_pred, gs_pred, 0, 1, 0, 0, show_legend=show_legend_predictive, show_inset=args.show_loglik_bars,
           legend_path=f"{FIGURES_DIR}/reversal_learning_predictive{TAG}_legend.png")
plotting_utils.save_panel(fig_pred, f"{FIGURES_DIR}/reversal_learning_predictive{TAG}.png", figsize=FIGSIZE_ALONE)
plt.close(fig_pred)
print(f"Saved reversal_learning_predictive{TAG}.png")

# 5c. Generative panel alone
fig_gen = plt.figure(figsize=FIGSIZE_ALONE)
plotting_utils.set_dynamic_fontsize(fig_width=FIGSIZE_ALONE[0], base_font=BASE_FONT)
gs_gen = GridSpec(2, 1, height_ratios=[0.12, 1], hspace=0.08,
                   top=GS_TOP, bottom=0.13, left=0.13, right=0.97)
draw_panel(fig_gen, gs_gen, 0, 1, 0, 1, show_legend=show_legend_generative, show_inset=False,
           legend_path=f"{FIGURES_DIR}/reversal_learning_generative{TAG}_legend.png")
plotting_utils.save_panel(fig_gen, f"{FIGURES_DIR}/reversal_learning_generative{TAG}.png", figsize=FIGSIZE_ALONE)
plt.close(fig_gen)
print(f"Saved reversal_learning_generative{TAG}.png")
