"""
Reversal-learning task simulation + Repetition / Win-Stay-Lose-Shift (WSLS)
model comparison, replicating a two-panel figure:

  (left)  Predictive performance  -- models fit trial-by-trial to the
          "real" choice data (i.e. fed the actual choice/outcome history
          and scored on how well they predict the next choice).
  (right) Generative performance  -- models run forward on their own,
          using only the fitted parameters + the task's true reward
          contingencies, to see what behavior they *produce*.

Ground truth "real" behavior is generated by a Rescorla-Wagner (delta-rule)
agent whose latent Q-values are corrupted by additive Gaussian noise at
choice time (probit-style choice rule, NOT softmax) -- standing in for
real subject data. See `simulate_qlearning_agent` below.

Task: 100 trials, two options (A, B). Reward probabilities are 80/20 in
favor of A for trials 1-50, then reverse to 20/80 (favoring B) for trials
51-100 (reversal at trial 50).
"""

import random

import numpy as np
import pandas as pd
from scipy.optimize import minimize

rng_global = np.random.default_rng(0)


class ProbabilisticWinStayLoseSwitch:
    """
    A probabilistic version of the Win-Stay/Lose-Switch (WS-LS) model.

    Attributes:
    - actions (list): A list of possible actions the agent can choose from.
    - current_action: The action currently being used by the agent.
    - p_stay_win (float): Probability of staying with the same action after a win.
    - p_stay_loss (float): Probability of staying with the same action after a loss.
    """

    def __init__(self, actions, p_stay_win=0.9, p_stay_loss=0.1):
        self.actions = actions
        self.current_action = random.choice(actions)  # Start with a random action
        self.p_stay_win = p_stay_win
        self.p_stay_loss = p_stay_loss

    def choose_action(self):
        """Return the current action."""
        return self.current_action

    def update(self, outcome):
        if outcome:  # If win
            if random.random() > self.p_stay_win:  # With probability (1 - p_stay_win), switch
                self._switch_action()
        else:  # If loss
            if random.random() > self.p_stay_loss:  # With probability (1 - p_stay_loss), switch
                self._switch_action()

    def _switch_action(self):
        """Switch to a different action."""
        other_actions = [a for a in self.actions if a != self.current_action]
        if other_actions:
            self.current_action = random.choice(other_actions)


class ActionModel:
    def __init__(self, actions, p_stay):
        self.actions = actions  # List of possible actions, e.g., ['walk', 'talk', 'run']
        self.p_stay = p_stay    # Probability of staying with the same action, e.g., 0.7
        self.current_action = random.choice(actions)  # Start with a random action

    def next_action(self):
      if random.random() < self.p_stay:
        return self.current_action  # Repeat the same action
      else:
          other_actions = [a for a in self.actions if a != self.current_action]
          self.current_action = random.choice(other_actions) if other_actions else self.current_action
          return self.current_action  # Choose a new action, or stay if no others


    def simulate(self, steps):
        return [self.next_action() for _ in range(steps)]  # Simulate for a number of steps

# ----------------------------------------------------------------------
# Task
# ----------------------------------------------------------------------

N_TRIALS = 30
REVERSAL = 15         # 1-indexed: trials 1..50 block 1, 51..100 block 2
P_HIGH = 0.8
P_LOW = 0.2

def reward_prob_A(t, reversal_points=(REVERSAL,)):
    """t is 0-indexed trial number. Returns P(reward=1 | choose A).
    `reversal_points` is a sorted tuple of 0-indexed trial numbers at which
    the currently-favored option flips (A->B->A->...); passing more than one
    point supports multi-block real-data schedules (e.g. the Waltmann PRLT
    design), not just the single-reversal simulated task."""
    n_flips = sum(1 for r in reversal_points if t >= r)
    return P_HIGH if n_flips % 2 == 0 else P_LOW

def reward_prob_B(t, reversal_points=(REVERSAL,)):
    return P_LOW if reward_prob_A(t, reversal_points) == P_HIGH else P_HIGH


# ----------------------------------------------------------------------
# Real data: Waltmann PRLT human choice/reward histories, as an alternative
# to `simulate_qlearning_agent` below. Loaded from rl_waltmann/data/in/,
# columns subject, trial, correct, reward, choice, stim, reversal,
# choice_mapped (see rl_waltmann/generate_gen_plots.py, which consumes the
# same files and fixes REVERSAL_POINTS = (36, 56, 71, 86, 106), 1-indexed
# trial number of the first trial of each new block).
# ----------------------------------------------------------------------

def load_waltmann_data(csv_path, reversal_points_1idx=(36, 56, 71, 86, 106)):
    """Load real per-subject choice/reward histories and recode each
    subject's raw 2-option choice (1/2) onto a common 0/1 axis where 0
    always denotes the option that was correct in that subject's first
    block. This mirrors the counterbalancing-removal generate_gen_plots.py's
    compute_chose_preferred() does, but preserves true stay/switch structure
    (a constant per-subject relabeling, not a per-trial "was I correct"
    recoding) so the recoded sequence can be fit directly with
    fit_repetition/fit_wsls below, exactly as for the simulated agent.

    Returns:
        choices, rewards: (n_subjects, n_trials) int arrays, 0/1.
        subjects: sorted list of subject ids, rows of choices/rewards match.
        n_trials: int.
        reversal_points_0idx: tuple of 0-indexed trial numbers to pass into
            reward_prob_A/B and simulate_generative_wsls.
    """
    df = pd.read_csv(csv_path)
    subjects = sorted(df["subject"].unique())
    n_trials = int(df[df["subject"] == subjects[0]]["trial"].max())

    choices = np.zeros((len(subjects), n_trials), dtype=int)
    rewards = np.zeros((len(subjects), n_trials), dtype=int)
    for i, subj in enumerate(subjects):
        sdf = df[df["subject"] == subj].sort_values("trial")
        raw_choice = sdf["choice"].to_numpy() - 1  # 1/2 -> 0/1
        reward = sdf["reward"].to_numpy()
        correct = sdf["correct"].to_numpy()

        initial_pref = raw_choice[0] if correct[0] == 1 else 1 - raw_choice[0]
        recoded = raw_choice if initial_pref == 0 else 1 - raw_choice

        choices[i] = recoded
        rewards[i] = reward

    reversal_points_0idx = tuple(r - 1 for r in reversal_points_1idx)
    return choices, rewards, subjects, n_trials, reversal_points_0idx


# ----------------------------------------------------------------------
# Ground-truth "real" agent: Q-learning with additive Gaussian noise on
# the latent values (Palminteri, Wyart & Koechlin, 2017, TICS, Box 1 /
# Figure I procedure) -- NOT softmax. Each trial, independent N(0, sigma^2)
# noise is added to each option's Q-value, and the option with the higher
# noisy value is chosen (a probit-style choice rule).
# ----------------------------------------------------------------------

def simulate_qlearning_agent(n_subjects, alpha, noise_sd, rng):
    """Simulate n_subjects sessions of the task with a Q-learning agent
    (delta-rule updates, learning rate alpha) whose values are corrupted
    by additive Gaussian noise (std noise_sd) at the moment of choice.
    Returns choices (0=A,1=B) and rewards, shape (n_subjects, N_TRIALS).
    """
    choices = np.zeros((n_subjects, N_TRIALS), dtype=int)
    rewards = np.zeros((n_subjects, N_TRIALS), dtype=int)

    for s in range(n_subjects):
        Q = np.array([0.5, 0.5])  # initial value estimates for A, B
        for t in range(N_TRIALS):
            noisy_Q = Q + rng.normal(0.0, noise_sd, size=2)
            c = 0 if noisy_Q[0] > noisy_Q[1] else 1
            p_r = reward_prob_A(t) if c == 0 else reward_prob_B(t)
            r = 1 if rng.random() < p_r else 0
            Q[c] += alpha * (r - Q[c])
            choices[s, t] = c
            rewards[s, t] = r
    return choices, rewards


# ----------------------------------------------------------------------
# Model 1: Repetition (choice history only, no outcome dependence)
# ----------------------------------------------------------------------

def fit_repetition(choices):
    """closed-form MLE: rho = fraction of trials where c_t == c_{t-1}."""
    stay = (choices[1:] == choices[:-1])
    rho = np.clip(stay.mean(), 1e-3, 1 - 1e-3)
    return rho

def predictive_curve_repetition(choices, rho):
    """P(choose A) predicted at each trial, given actual choice history."""
    T = choices.shape[0]
    pred = np.empty(T)
    pred[0] = 0.5
    for t in range(1, T):
        prev = choices[t - 1]
        pred[t] = rho if prev == 0 else (1 - rho)
    return pred

def fit_repetition_numeric(choices, initial_guess=0.5):
    """Same MLE as fit_repetition, but via numerical NLL minimization
    (scipy L-BFGS-B) instead of the closed form. Should converge to the
    same rho -- provided as a cross-check / template for models without
    a closed-form solution."""
    T = choices.shape[0]
    def nll(params):
        pred = predictive_curve_repetition(choices, params[0])
        return -mean_trial_loglik(choices, pred) * (T - 1)
    result = minimize(nll, x0=[initial_guess], bounds=[(1e-3, 1 - 1e-3)], method="L-BFGS-B")
    return result.x[0]

def simulate_generative_repetition(rho, n_sims, rng, n_trials=N_TRIALS):
    """Model generates its own choices; task rewards are irrelevant to it.
    Uses the ActionModel agent above (stdlib `random`, seeded separately
    from the numpy `rng` used elsewhere in the pipeline)."""
    out = np.zeros((n_sims, n_trials), dtype=int)
    for i in range(n_sims):
        agent = ActionModel(actions=[0, 1], p_stay=rho)
        out[i] = agent.simulate(n_trials)
    return out


# ----------------------------------------------------------------------
# Model 2: Win-Stay-Lose-Shift (single-parameter, probabilistic,
# outcome dependent)
# ----------------------------------------------------------------------

def fit_wsls(choices, rewards):
    """Single-parameter WS-LS, as in Palminteri, Wyart & Koechlin (2017):
    chooses the WS-LS-recommended action (stay if previous trial was
    rewarded, switch otherwise) with probability P, and the other action
    with probability 1-P. Closed-form MLE: P = fraction of trials where
    the actual choice matches the recommended action."""
    prev_c, prev_r = choices[:-1], rewards[:-1]
    cur_c = choices[1:]
    recommended = np.where(prev_r == 1, prev_c, 1 - prev_c)
    P = np.clip((cur_c == recommended).mean(), 1e-3, 1 - 1e-3)
    return P

def predictive_curve_wsls(choices, rewards, P):
    T = choices.shape[0]
    pred = np.empty(T)
    pred[0] = 0.5
    for t in range(1, T):
        prev_c, prev_r = choices[t - 1], rewards[t - 1]
        recommended = prev_c if prev_r == 1 else (1 - prev_c)
        pred[t] = P if recommended == 0 else (1 - P)
    return pred

def fit_wsls_numeric(choices, rewards, initial_guess=0.5):
    """Same MLE as fit_wsls, but via numerical NLL minimization (scipy
    L-BFGS-B) instead of the closed form. Should converge to the same P
    -- provided as a cross-check / template for models without a
    closed-form solution."""
    T = choices.shape[0]
    def nll(params):
        pred = predictive_curve_wsls(choices, rewards, params[0])
        return -mean_trial_loglik(choices, pred) * (T - 1)
    result = minimize(nll, x0=[initial_guess], bounds=[(1e-3, 1 - 1e-3)], method="L-BFGS-B")
    return result.x[0]

def simulate_generative_wsls(P, n_sims, rng, n_trials=N_TRIALS, reversal_points=(REVERSAL,)):
    """Model generates choices AND receives real task feedback for them,
    reacting to it with its fitted stay/shift probability. Uses the
    ProbabilisticWinStayLoseSwitch agent above to pick/switch actions;
    task reward draws use the numpy `rng` for consistency with the rest
    of the pipeline (the agent's own action selection uses the stdlib
    `random` module, as written)."""
    out = np.zeros((n_sims, n_trials), dtype=int)
    for i in range(n_sims):
        agent = ProbabilisticWinStayLoseSwitch(
            actions=[0, 1], p_stay_win=P, p_stay_loss=1 - P
        )
        for t in range(n_trials):
            c = agent.choose_action()
            p_r = reward_prob_A(t, reversal_points) if c == 0 else reward_prob_B(t, reversal_points)
            r = 1 if rng.random() < p_r else 0
            out[i, t] = c
            agent.update(bool(r))
    return out


# ----------------------------------------------------------------------
# Log-likelihood (predictive fit quality)
# ----------------------------------------------------------------------

def mean_trial_loglik(choices, pred_p_choose_A):
    """Average per-trial log P(actual choice | model), trials 2..T."""
    actual_A = (choices[1:] == 0)
    p = pred_p_choose_A[1:]
    p = np.clip(p, 1e-6, 1 - 1e-6)
    ll = np.where(actual_A, np.log(p), np.log(1 - p))
    return ll.mean()


if __name__ == "__main__":
    rng = np.random.default_rng(1)
    for alpha in [0.1, 0.15, 0.2, 0.25]:
        for noise_sd in [0.1, 0.2, 0.3, 0.4]:
            ch, rw = simulate_qlearning_agent(100, alpha, noise_sd, rng)
            choose_A_rate = (ch == 0).mean(axis=0)
            print(f"alpha={alpha} noise_sd={noise_sd}  early(1-5)={choose_A_rate[:5].mean():.2f} "
                  f"peak(10-49)={choose_A_rate[10:49].mean():.2f} "
                  f"late(90-100)={choose_A_rate[90:].mean():.2f}")
